version: "3.8"
services:
  drupal:
    image: custom-drupal
    build: .
    ports:
      - "8080:80"
    restart: always
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10.5
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=test
      - MARIADB_USER=root
      - MARIADB_PASSWORD=root
    volumes:
      - drupal-data:/var/lib/mysql:Z
    restart: always

volumes:
  drupal-data:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
